CREATE DATABASE DB_CIDADE_DOS_VEGETAIS;
USE DB_CIDADE_DOS_VEGETAIS;
CREATE TABLE TB_CATEGORIAS(
ID BIGINT AUTO_INCREMENT,
CATEGORIA CHAR (100),
REGIAO CHAR (155),
PRIMARY KEY (ID));

CREATE TABLE TB_PRODUTOS(
ID BIGINT AUTO_INCREMENT,
PRIMARY KEY (ID),
NOME CHAR (100),
QUANTIDADE INT,
PRECO DECIMAL,
OPCAO CHAR(155),
CATEGORIAS_ID BIGINT,
FOREIGN KEY (CATEGORIAS_ID) REFERENCES TB_CATEGORIAS(ID));

INSERT INTO TB_CATEGORIAS(CATEGORIA,REGIAO)
VALUE ("HORTALIÇAS","REFRIGERADOR");

INSERT INTO TB_CATEGORIAS(CATEGORIA,REGIAO)
VALUE ("VERDURAS","CORREDOR 1");

INSERT INTO TB_CATEGORIAS(CATEGORIA,REGIAO)
VALUE ("LEGUMES","CORREDOR 2");

INSERT INTO TB_CATEGORIAS(CATEGORIA,REGIAO)
VALUE ("FRUTAS","CORREDOR 3");

INSERT INTO TB_CATEGORIAS(CATEGORIA,REGIAO)
VALUE ("PRODUTOS A GRANEL","CORREDOR 4");

SELECT * FROM TB_CATEGORIAS ;

INSERT INTO TB_PRODUTOS(NOME,QUANTIDADE,PRECO,OPCAO,CATEGORIAS_ID)
VALUE ("MORNGO",150,5.50,"HIGIENIZADOS",4);

INSERT INTO TB_PRODUTOS (NOME,QUANTIDADE,PRECO,OPCAO,CATEGORIAS_ID)
VALUE ("ALFACE",20,4,"HIGIENIZADOS",1);

INSERT INTO TB_PRODUTOS (NOME,QUANTIDADE,PRECO,OPCAO,CATEGORIAS_ID)
VALUE ("CEBOLA",200,0.50,"DESCASCADAS",2);

INSERT INTO TB_PRODUTOS (NOME,QUANTIDADE,PRECO,OPCAO,CATEGORIAS_ID)
VALUE ("MILHO",300,1.50,"HIGIENIZADOS",2);

INSERT INTO TB_PRODUTOS (NOME,QUANTIDADE,PRECO,OPCAO,CATEGORIAS_ID)
VALUE ("ABOBRINHA",200,.75,"EMBALADAS",3);

INSERT INTO TB_PRODUTOS (NOME,QUANTIDADE,PRECO,OPCAO,CATEGORIAS_ID)
VALUE ("ABOBORA",100,5,"EMBALADAS",3);

INSERT INTO TB_PRODUTOS (NOME,QUANTIDADE,PRECO,OPCAO,CATEGORIAS_ID)
VALUE ("MELÃO",200,10,"CORTADOS",4);

INSERT INTO TB_PRODUTOS (NOME,QUANTIDADE,PRECO,OPCAO,CATEGORIAS_ID)
VALUE ("AVEIA",500,1,"GRAMAS",5);

SELECT * FROM TB_PRODUTOS;

SELECT * FROM TB_PRODUTOS WHERE PRECO > 50;

SELECT * FROM TB_PRODUTOS WHERE PRECO > 5 AND PRECO < 50;

SELECT * FROM TB_PRODUTOS WHERE NOME LIKE "%C%" ;

SELECT * FROM TB_PRODUTOS INNER JOIN TB_CATEGORIAS ON TB_CATEGORIAS.ID = TB_PRODUTOS.CATEGORIAS_ID;

SELECT NOME,CATEGORIA FROM TB_PRODUTOS INNER JOIN TB_CATEGORIAS ON TB_CATEGORIAS.ID = TB_PRODUTOS.CATEGORIAS_ID;
