CREATE DATABASE DB_FARMACIA_BEM_ESTAR;
USE DB_FARMACIA_BEM_ESTAR;
CREATE TABLE TB_CATEGORIAS(
ID BIGINT AUTO_INCREMENT,
CATEGORIA CHAR (150),
REGIAO CHAR (100),
PRIMARY KEY (ID)
);

CREATE TABLE TB_PRODUTOS(
ID BIGINT AUTO_INCREMENT,
PRIMARY KEY (ID),
DESCRICAO CHAR(200),
QUANTIDADE INT,
PRECO DECIMAL (8,2),
PROMOCAO INT,
CATEGORIAS_ID BIGINT,
FOREIGN KEY (CATEGORIAS_ID) REFERENCES TB_CATEGORIAS(ID)
);

INSERT INTO TB_CATEGORIAS (CATEGORIA,REGIAO)
VALUE ("PERFUMARIA","SETOR CENTRAL");

INSERT INTO TB_CATEGORIAS (CATEGORIA,REGIAO)
VALUE ("MEDICAMENTOS","SETOR CENTRAL"); 

INSERT INTO TB_CATEGORIAS (CATEGORIA,REGIAO)
VALUE ("INFANTIL","SETOR SUL");

INSERT INTO TB_CATEGORIAS (CATEGORIA,REGIAO)
VALUE ("ALIMENTÍCIOS","SETOR NORTE");

INSERT INTO TB_CATEGORIAS (CATEGORIA,REGIAO)
VALUE ("SENIOR","SETOR SUL");

SELECT * FROM TB_CATEGORIAS ;

INSERT INTO TB_PRODUTOS (DESCRICAO,QUANTIDADE,PRECO,PROMOCAO,CATEGORIAS_ID)
VALUE ("ESMALTE",20,4.50,0,5);

INSERT INTO TB_PRODUTOS (DESCRICAO,QUANTIDADE,PRECO,PROMOCAO,CATEGORIAS_ID)
VALUE ("DIPIRONA",200,3.50,10,6);

INSERT INTO TB_PRODUTOS (DESCRICAO,QUANTIDADE,PRECO,PROMOCAO,CATEGORIAS_ID)
VALUE ("FRALDAS P",20,49.50,5,7);

INSERT INTO TB_PRODUTOS (DESCRICAO,QUANTIDADE,PRECO,PROMOCAO,CATEGORIAS_ID)
VALUE ("BARRINHA DE WHEY",50,2.50,0,8);

INSERT INTO TB_PRODUTOS (DESCRICAO,QUANTIDADE,PRECO,PROMOCAO,CATEGORIAS_ID)
VALUE ("BENGALA",3,78.5,2,9);

INSERT INTO TB_PRODUTOS (DESCRICAO,QUANTIDADE,PRECO,PROMOCAO,CATEGORIAS_ID)
VALUE ("POMADA",50,55,12,7);

INSERT INTO TB_PRODUTOS (DESCRICAO,QUANTIDADE,PRECO,PROMOCAO,CATEGORIAS_ID)
VALUE ("ESCOVA DE CABELO",4,32.50,6,5);

INSERT INTO TB_PRODUTOS (DESCRICAO,QUANTIDADE,PRECO,PROMOCAO,CATEGORIAS_ID)
VALUES ("ESPARADRAPO",120,15,10,6);

DELETE FROM TB_CATEGORIAS WHERE ID = 1;
DELETE FROM TB_CATEGORIAS WHERE ID = 2;
DELETE FROM TB_CATEGORIAS WHERE ID = 3;
DELETE FROM TB_CATEGORIAS WHERE ID = 4;

SELECT * FROM TB_PRODUTOS;

SELECT * FROM TB_PRODUTOS WHERE PRECO > 50;

SELECT * FROM TB_PRODUTOS WHERE PRECO > 5 AND PRECO < 60 ;

SELECT * FROM TB_PRODUTOS WHERE DESCRICAO LIKE "%C%";

SELECT * FROM TB_PRODUTOS INNER JOIN TB_CATEGORIAS ON TB_PRODUTOS.CATEGORIAS_ID = TB_CATEGORIAS.ID ;

SELECT DESCRICAO,PROMOCAO FROM TB_PRODUTOS INNER JOIN TB_CATEGORIAS  ON TB_CATEGORIAS.ID = TB_PRODUTOS.CATEGORIAS_ID;
