CREATE DATABASE BASE_FUNCIONARIOS;
USE BASE_FUNCIONARIOS;

CREATE TABLE TB_FUNCIONARIOS (
ID BIGINT AUTO_INCREMENT,
NOME VARCHAR(1000),
IDADE INT,
GENERO CHAR(100),
FUNCAO CHAR (255),
SALARIO INT,
PRIMARY KEY (ID)
);

INSERT INTO TB_FUNCIONARIOS (NOME,IDADE,GENERO,FUNCAO,SALARIO)
VALUE ("CRISTALY",25,"FEMININO","BACKEND",3500);

INSERT INTO TB_FUNCIONARIOS (NOME,IDADE,GENERO,FUNCAO,SALARIO)
VALUE("MARIANA",30,"FEMININO","BANCO DE DADOS",3600);

INSERT INTO TB_FUNCIONARIOS (NOME,IDADE,GENERO,FUNCAO,SALARIO)
VALUE ("STEPHANY",26,"FEMININO","FULLSTACK",3800);

INSERT INTO TB_FUNCIONARIOS(NOME,IDADE,GENERO,FUNCAO,SALARIO)
VALUE("PAULA",22,"FEMININO","FULLSTACK",3600);

INSERT INTO TB_FUNCIONARIOS (NOME,IDADE,GENERO,FUNCAO,SALARIO)
VALUE ("SCARLET",26,"FEMININO","FRONTEND",2000);

INSERT INTO TB_FUNCIONARIOS (NOME,IDADE,GENERO,FUNCAO,SALARIO)
VALUE ("ANDERSON",28,"MASCULINO","BANCO DE DADOS",4000);

INSERT INTO TB_FUNCIONARIOS (NOME,IDADE,GENERO,FUNCAO,SALARIO)
VALUE ("RAPHAEL",26,"MASCULINO","ESTAGIARIO",1500);

SELECT *FROM TB_FUNCIONARIOS;

SELECT * FROM TB_FUNCIONARIOS WHERE SALARIO > 2000;

SELECT * FROM TB_FUNCIONARIOS WHERE SALARIO <= 2000;

SET SQL_SAFE_UPDATES = 0;

UPDATE TB_FUNCIONARIOS SET SALARIO = 1800 WHERE ID = 6;

UPDATE TB_FUNCIONARIOS SET SALARIO = 2200 WHERE ID = 6;