CREATE DATABASE DB_ESCOLA;
USE DB_ESCOLA;
CREATE TABLE TB_ALUNOS (
ID BIGINT AUTO_INCREMENT,
NOME VARCHAR(1000),
IDADE INT,
MATEMATICA INT,
PORTUGUES INT,
BIMESTRE INT,
NOTA INT,
PRIMARY KEY (ID)
);


INSERT INTO TB_ALUNOS (NOME,IDADE,MATEMATICA,PORTUGUES,BIMESTRE,NOTA)
VALUE ("GABRIELLE ALVES",17,7,6,2,6);

INSERT INTO TB_ALUNOS (NOME,IDADE,MATEMATICA,PORTUGUES,BIMESTRE,NOTA)
VALUE ("ANA LUIZA ALVES",15,5,8,2,6);

INSERT INTO TB_ALUNOS (NOME,IDADE,MATEMATICA,PORTUGUES,BIMESTRE,NOTA)
VALUE ("VITORIA ALVES",15,8,8,2,8);

INSERT INTO TB_ALUNOS (NOME,IDADE,MATEMATICA,PORTUGUES,BIMESTRE,NOTA)
VALUE ("NATA ALVES",13,5,7,2,6);

INSERT INTO TB_ALUNOS (NOME,IDADE,MATEMATICA,PORTUGUES,BIMESTRE,NOTA)
VALUE ("EMANUELLY ALVES",8,8,9,2,8);

INSERT INTO TB_ALUNOS (NOME,IDADE,MATEMATICA,PORTUGUES,BIMESTRE,NOTA)
VALUE ("SOPHIA ALVES",5,7,9,2,8);

INSERT INTO TB_ALUNOS (NOME,IDADE,MATEMATICA,PORTUGUES,BIMESTRE,NOTA)
VALUE ("DAVI HENRIQUE ALVES",3,8,8,2,8);

INSERT INTO TB_ALUNOS (NOME,IDADE,MATEMATICA,PORTUGUES,BIMESTRE,NOTA)
VALUE ("ISABELLA VITORIA ALVES",9,7,8,2,7);

SELECT * FROM TB_ALUNOS;

SELECT * FROM TB_ALUNOS WHERE NOTA > 7 ;

SELECT * FROM TB_ALUNOS WHERE NOTA < 7;

SET SQL_SAFE_UFDATES = 0;

UPDATE TB_ALUNOS SET NOTA = 8 WHERE ID = 1;
UPDATE TB_ALUNOS SET NOTA = 9 WHERE ID = 2;
