-- MySQL Script generated by MySQL Workbench
-- Tue Sep 27 19:50:12 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`TB_TEMA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TB_TEMA` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT,
  `DESCRICAO` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TB_USUARIOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TB_USUARIOS` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(255) NOT NULL,
  `USUARIO` VARCHAR(255) NOT NULL,
  `SENHA` VARCHAR(255) NOT NULL,
  `FOTO` VARCHAR(255) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TB_POSTAGENS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TB_POSTAGENS` (
  `ID` BIGINT NOT NULL,
  `TITULO` VARCHAR(100) NOT NULL,
  `TEXTO` VARCHAR(1000) NOT NULL,
  `DATE` DATE NULL,
  `FOTO` VARCHAR(255) NULL,
  `TEMA_ID` BIGINT NOT NULL,
  `USUARIOS_ID` BIGINT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_TB_POSTAGENS_TB_TEMA_idx` (`TEMA_ID` ASC) VISIBLE,
  INDEX `fk_TB_POSTAGENS_TB_USUARIOS1_idx` (`USUARIOS_ID` ASC) VISIBLE,
  CONSTRAINT `fk_TB_POSTAGENS_TB_TEMA`
    FOREIGN KEY (`TEMA_ID`)
    REFERENCES `mydb`.`TB_TEMA` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TB_POSTAGENS_TB_USUARIOS1`
    FOREIGN KEY (`USUARIOS_ID`)
    REFERENCES `mydb`.`TB_USUARIOS` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
